version: '3.8'

services:
  collection-service:
    build: .
    container_name: collection_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Database Configuration
      - DATABASE_URL=mysql+asyncmy://u792485705_tyts:oA5843eC@srv1502.hstgr.io:3306/u792485705_maintyt
      
      # JWT Authentication
      - AUTH_JWKS_URL=https://auth.takeyourtrade.com/.well-known/jwks.json
      - JWT_AUDIENCE=collection-service
      - JWT_ISSUER=https://auth.takeyourtrade.com
      
      # CORS Configuration
      - CORS_ORIGINS=["https://app.takeyourtrade.com","https://takeyourtrade.com","https://www.takeyourtrade.com","http://localhost:3000"]
      
      # Application Info
      - APP_NAME=Collection Service
      - APP_VERSION=1.0.0
      - DEBUG=false
    
    networks:
      - collection_network

networks:
  collection_network:
    driver: bridge

