version: '3.8'

services:
  collection-service:
    build: .
    container_name: collection_service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Database Configuration (OBBLIGATORIO)
      - DATABASE_URL=${DATABASE_URL}
      
      # JWT Authentication
      - AUTH_JWKS_URL=${AUTH_JWKS_URL:-https://auth.takeyourtrade.com/.well-known/jwks.json}
      - JWT_AUDIENCE=${JWT_AUDIENCE:-collection-service}
      - JWT_ISSUER=${JWT_ISSUER:-https://auth.takeyourtrade.com}
      
      # CORS Configuration (domini autorizzati)
      - CORS_ORIGINS=${CORS_ORIGINS:-["https://app.takeyourtrade.com","https://takeyourtrade.com","https://www.takeyourtrade.com"]}
      
      # Application Info
      - APP_NAME=Collection Service
      - APP_VERSION=1.0.0
      - DEBUG=${DEBUG:-false}
    
    networks:
      - collection_network

networks:
  collection_network:
    driver: bridge

